(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* This is needed so that the .m file can be called from any directory and not have any directory issues. *)
packageDir=DirectoryName[$InputFileName];
(* packageDir=NotebookDirectory[];
If this is uncommented then the file can be loaded locally and one can explicitly tests the various functions.
*)
dataFile[name_]:=FileNameJoin[{packageDir,"..","BasicModules_data",name}];


(* ::Input::Initialization:: *)
(* Code based on [2511.04747] by M.Escudero, G.Jackson, M.Laine and S.Sandner 
v1 from M.Escudero in [1812.05605] and [2001.04466] *)

(* If not initialized set up to default values *)
If[ValueQ[flagQED],,flagQED="FILE"];
If[ValueQ[orderQED],,orderQED=3];
If[ValueQ[nBesselmaxQED],,nBesselmaxQED=30];
If[ValueQ[flagthermo],,flagthermo="BESSEL"];
If[ValueQ[nBesselmaxBSM],,nBesselmaxBSM=30];


(* ::Input::Initialization:: *)
If[ValueQ[GF],Print["Using your already defined GF value = ",NumberForm[GF,4]," in \!\(\*SuperscriptBox[\(MeV\), \(-2\)]\)"],GF=1.1663787 10^-11;];  (* GFermi in MeV^-2 *)

If[ValueQ[eEM],Print["Using your already defined eEM value = ",NumberForm[eEM,4]],eEM=Sqrt[4\[Pi] \[Alpha]]/.\[Alpha]->1/137.035999084;];(* Electromagnetic coupling, used for QED corrections *)

If[ValueQ[m0],Print["Using your already defined m0 value = ",NumberForm[m0,4]," in MeV"],m0=1];(* Used to generate a dimensionless scale factor *)

If[ValueQ[me],Print["Using your already defined me value = ",NumberForm[me,4]," in MeV"],me = 0.51099895; ];(* Electron mass in MeV *)

If[ValueQ[Mpl],Print["Using your already defined Mpl value = ",NumberForm[Mpl,4]," in MeV"],Mpl = 1.220890 10^19 10^3 ; ];(* Planck mass in MeV *)

If[ValueQ[geL],Print["Using your already defined low-energy neutrino couplings =",geL," ",geR," ",gmuL, " ",gmuR],geL=0.727;
geR=0.233;
gmuL=-0.273;
gmuR=0.233;];(* Low energy effective coupling constants as taken from 1303.5522 + the CC part for \[Nu]e *)

FacMeVtos1=1/(6.58212 10^-16 10^-6); (* This is used to convert MeV to s^-1 *)


(* ::Input::Initialization:: *)
(* Start by taking them to be 0 just in case *)
ClearAll[Pint,dPintdT,d2PintdT2];
Pint[T_]:=0;
dPintdT[T_]:=0;
d2PintdT2[T_]:=0;

(* Just load and interpolate the tabulated functions from the file *)
SetDirectory[NotebookDirectory[]];

If[orderQED!=0&&6>=orderQED>=2&&orderQED\[Element]Integers&&FileExistsQ[dataFile["QED_p_int.dat"]]==True,

ClearAll[Pintinterpol,dPintdTinterpol,d2PintdT2interpol];
ClearAll[Pint,dPintdT,d2PintdT2];

If[orderQED==2,
Pintinterpol=Interpolation[{#[[1]],#[[3]]}&/@Import[dataFile["QED_p_int.dat"],"Table",HeaderLines-> 3]];
dPintdTinterpol=Interpolation[{#[[1]],#[[3]]}&/@Import[dataFile["QED_dp_dT_int.dat"],"Table",HeaderLines-> 3]];
d2PintdT2interpol=Interpolation[{#[[1]],#[[3]]}&/@Import[dataFile["QED_d2p_dT2_int.dat"],"Table",HeaderLines-> 3]];
];

If[orderQED==3,
Pintinterpol=Interpolation[{#[[1]],#[[3]]+#[[5]]}&/@Import[dataFile["QED_p_int.dat"],"Table",HeaderLines-> 3]];
dPintdTinterpol=Interpolation[{#[[1]],#[[3]]+#[[5]]}&/@Import[dataFile["QED_dp_dT_int.dat"],"Table",HeaderLines-> 3]];
d2PintdT2interpol=Interpolation[{#[[1]],#[[3]]+#[[5]]}&/@Import[dataFile["QED_d2p_dT2_int.dat"],"Table",HeaderLines-> 3]];
];

If[orderQED==4,
Pintinterpol=Interpolation[{#[[1]],#[[3]]+#[[5]]+#[[6]]}&/@Import[dataFile["QED_p_int.dat"],"Table",HeaderLines-> 3]];
dPintdTinterpol=Interpolation[{#[[1]],#[[3]]+#[[5]]+#[[6]]}&/@Import[dataFile["QED_dp_dT_int.dat"],"Table",HeaderLines-> 3]];
d2PintdT2interpol=Interpolation[{#[[1]],#[[3]]+#[[5]]+#[[6]]}&/@Import[dataFile["QED_d2p_dT2_int.dat"],"Table",HeaderLines-> 3]];
];

If[orderQED==5,
Pintinterpol=Interpolation[{#[[1]],#[[3]]+#[[5]]+#[[6]]+#[[7]]}&/@Import[dataFile["QED_p_int.dat"],"Table",HeaderLines-> 3]];
dPintdTinterpol=Interpolation[{#[[1]],#[[3]]+#[[5]]+#[[6]]+#[[7]]}&/@Import[dataFile["QED_dp_dT_int.dat"],"Table",HeaderLines-> 3]];
d2PintdT2interpol=Interpolation[{#[[1]],#[[3]]+#[[5]]+#[[6]]+#[[7]]}&/@Import[dataFile["QED_d2p_dT2_int.dat"],"Table",HeaderLines-> 3]];
];

If[orderQED==6,
Pintinterpol=Interpolation[{#[[1]],#[[3]]+#[[4]]+#[[5]]+#[[6]]+#[[7]]}&/@Import[dataFile["QED_p_int.dat"],"Table",HeaderLines-> 3]];
dPintdTinterpol=Interpolation[{#[[1]],#[[3]]+#[[4]]+#[[5]]+#[[6]]+#[[7]]}&/@Import[dataFile["QED_dp_dT_int.dat"],"Table",HeaderLines-> 3]];
d2PintdT2interpol=Interpolation[{#[[1]],#[[3]]+#[[4]]+#[[5]]+#[[6]]+#[[7]]}&/@Import[dataFile["QED_d2p_dT2_int.dat"],"Table",HeaderLines-> 3]];
];

Pint[TTT_]:=Piecewise[{{Pintinterpol[TTT],5 10^-3<=TTT<=39.99}},0];
dPintdT[TTT_]:=Piecewise[{{dPintdTinterpol[TTT],5 10^-3<=TTT<=39.99}},0];
d2PintdT2[TTT_]:=Piecewise[{{d2PintdT2interpol[TTT],5 10^-3<=TTT<=39.99}},0];

res=Check[Pint,$Failed];
];



(* ::Input::Initialization:: *)
(* Full function case *)
If[flagQED=="FULL"&&orderQED!=0&&orderQED\[Element]Integers,
ClearAll[jof\[Tau],jpof\[Tau],Jof\[Tau],Yof\[Tau],kof\[Tau],Kof\[Tau],Zof\[Tau]];
jof\[Tau][\[Tau]_]:=1/\[Pi]^2 NIntegrate[Exp[Sqrt[\[Omega]^2+\[Tau]^2]]/(Exp[Sqrt[\[Omega]^2+\[Tau]^2]]+1)^2,{\[Omega],0,Infinity}];
jpof\[Tau][\[Tau]_]:=1/\[Pi]^2 NIntegrate[(-((E^Sqrt[\[Tau]^2+\[Omega]^2] (-1+E^Sqrt[\[Tau]^2+\[Omega]^2]) \[Tau])/((1+E^Sqrt[\[Tau]^2+\[Omega]^2])^3 Sqrt[\[Tau]^2+\[Omega]^2]))),{\[Omega],0,Infinity}];
Jof\[Tau][\[Tau]_]:=1/\[Pi]^2 NIntegrate[\[Omega]^2 Exp[Sqrt[\[Omega]^2+\[Tau]^2]]/(Exp[Sqrt[\[Omega]^2+\[Tau]^2]]+1)^2,{\[Omega],0,Infinity}];
Yof\[Tau][\[Tau]_]:=1/\[Pi]^2 NIntegrate[\[Omega]^4 Exp[Sqrt[\[Omega]^2+\[Tau]^2]]/(Exp[Sqrt[\[Omega]^2+\[Tau]^2]]+1)^2,{\[Omega],0,Infinity}];
kof\[Tau][\[Tau]_]:=1/\[Pi]^2 NIntegrate[1/Sqrt[\[Omega]^2+\[Tau]^2] 1/(Exp[Sqrt[\[Omega]^2+\[Tau]^2]]+1),{\[Omega],0,Infinity}];
Kof\[Tau][\[Tau]_]:=1/\[Pi]^2 NIntegrate[\[Omega]^2/Sqrt[\[Omega]^2+\[Tau]^2] 1/(Exp[Sqrt[\[Omega]^2+\[Tau]^2]]+1),{\[Omega],0,Infinity}];
Zof\[Tau][\[Tau]_]:=1/\[Pi]^2 NIntegrate[\[Omega]^4/Sqrt[\[Omega]^2+\[Tau]^2] 1/(Exp[Sqrt[\[Omega]^2+\[Tau]^2]]+1),{\[Omega],0,Infinity}];

];


(* Bessel Expansion case *)

If[flagQED=="BESSEL"&&nBesselmaxQED>10&&nBesselmaxQED\[Element]Integers&&orderQED!=0&&orderQED\[Element]Integers,
ClearAll[jof\[Tau],jpof\[Tau],Jof\[Tau],Yof\[Tau],kof\[Tau],Kof\[Tau],Zof\[Tau]];
jof\[Tau][\[Tau]_]:=1/\[Pi]^2 Sum[(-1)^n (1+n) \[Tau] BesselK[1,(1+n) \[Tau]],{n,0,nBesselmaxQED}];
jpof\[Tau][\[Tau]_]:=1/\[Pi]^2 Sum[-(-1)^n (1+n)^2 \[Tau] BesselK[0,(1+n) \[Tau]],{n,0,nBesselmaxQED}];
Jof\[Tau][\[Tau]_]:=1/\[Pi]^2 Sum[(-1)^n \[Tau]^2 BesselK[2,(1+n) \[Tau]],{n,0,nBesselmaxQED}];
Yof\[Tau][\[Tau]_]:=1/\[Pi]^2 Sum[(3 (-1)^n \[Tau]^3 BesselK[3,(1+n) \[Tau]])/(1+n),{n,0,nBesselmaxQED}];
kof\[Tau][\[Tau]_]:=1/\[Pi]^2 Sum[(-1)^n BesselK[0,(1+n) \[Tau]],{n,0,nBesselmaxQED}];
Kof\[Tau][\[Tau]_]:=1/\[Pi]^2 Sum[((-1)^n \[Tau] BesselK[1,(1+n) \[Tau]])/(1+n),{n,0,nBesselmaxQED}];
Zof\[Tau][\[Tau]_]:=1/\[Pi]^2 Sum[(3 (-1)^n \[Tau]^2 BesselK[2,(1+n) \[Tau]])/(1+n)^2,{n,0,nBesselmaxQED}];
];


(* ::Input::Initialization:: *)
If[(flagQED=="FULL"||(flagQED=="BESSEL"&&nBesselmaxQED>10))&&orderQED!=0&&orderQED\[Element]Integers,

ClearAll[Pint,dPintdT,d2PintdT2];
ClearAll[G10,G20,G12,G22,G13,G23,G14,c4,G24,G15,c5,G25,Ptil0,Ptil2,Ptil3,Ptil4,Ptil5];

G10[\[Tau]_]:=\[Tau]*Jof\[Tau][\[Tau]];
G20[\[Tau]_]:=\[Tau]^2*Jof\[Tau][\[Tau]]+Yof\[Tau][\[Tau]]+(2\[Pi]^2)/15;

G12[\[Tau]_]:=-((eEM^2 \[Tau])/12)(jof\[Tau][\[Tau]](1+6Kof\[Tau][\[Tau]])+2kof\[Tau][\[Tau]](1+3Jof\[Tau][\[Tau]]));
G22[\[Tau]_]:=-(eEM^2/12)(3Jof\[Tau][\[Tau]]+2(Jof\[Tau][\[Tau]]+Kof\[Tau][\[Tau]])(1+3Jof\[Tau][\[Tau]])+\[Tau]^2 jof\[Tau][\[Tau]](1+6Kof\[Tau][\[Tau]]));

G13[\[Tau]_]:=(eEM^3 \[Tau])/(4\[Pi]) Sqrt[Jof\[Tau][\[Tau]]/2](2jof\[Tau][\[Tau]]-\[Tau] jpof\[Tau][\[Tau]]+(\[Tau]^2 jof\[Tau][\[Tau]]^2)/(2Jof\[Tau][\[Tau]]));
G23[\[Tau]_]:=eEM^3/(4\[Pi]) Sqrt[Jof\[Tau][\[Tau]]/2](8 Jof\[Tau][\[Tau]]+5\[Tau]^2 jof\[Tau][\[Tau]]-\[Tau]^3 jpof\[Tau][\[Tau]]+(\[Tau]^4 jof\[Tau][\[Tau]]^2)/(2Jof\[Tau][\[Tau]]));

G14[\[Tau]_]:=-(eEM^2/(6\[Pi]^2))G12[\[Tau]]Log[\[Tau]]-eEM^4/(36\[Pi]^2) ((Jof\[Tau][\[Tau]]+6(Jof\[Tau][\[Tau]]-Kof\[Tau][\[Tau]])Kof\[Tau][\[Tau]])/\[Tau]);
c4=-0.00159412;
G24[\[Tau]_]:=-(eEM^2/(6\[Pi]^2))G22[\[Tau]]Log[\[Tau]]+(2 c4 eEM^4 \[Pi]^2)/15-eEM^4/(72\[Pi]^2) (3Kof\[Tau][\[Tau]](1-Kof\[Tau][\[Tau]])+2Jof\[Tau][\[Tau]](1+6Kof\[Tau][\[Tau]]));

G15[\[Tau]_]:=-(eEM^2/(4\[Pi]^2))G13[\[Tau]]Log[\[Tau]]+eEM^5/(24\[Pi]^3) Sqrt[Jof\[Tau][\[Tau]]/2]((4Jof\[Tau][\[Tau]]+3\[Tau]^2 jof\[Tau][\[Tau]])/\[Tau]);
c5=-0.000697166;
G25[\[Tau]_]:=-(eEM^2/(4\[Pi]^2))G23[\[Tau]]Log[\[Tau]]+(2 c5 eEM^5 \[Pi]^2)/15+eEM^5/(24\[Pi]^3) Sqrt[Jof\[Tau][\[Tau]]/2](7Jof\[Tau][\[Tau]]+3\[Tau]^2 jof\[Tau][\[Tau]]);

Ptil0[\[Tau]_]:=\[Pi]^2/45+(2Zof\[Tau][\[Tau]])/3;
Ptil2[\[Tau]_]:=-(eEM^2/2)(1/3+Kof\[Tau][\[Tau]])Kof\[Tau][\[Tau]];
Ptil3[\[Tau]_]:=eEM^3/(3Sqrt[2]\[Pi]) (Jof\[Tau][\[Tau]])^(3/2);
Ptil4[\[Tau]_]:=-(eEM^2/(6\[Pi]^2))Ptil2[\[Tau]]Log[\[Tau]]+(c4 eEM^4 \[Pi]^2)/45 ;
Ptil5[\[Tau]_]:=-(eEM^2/(4\[Pi]^2))Ptil3[\[Tau]]Log[\[Tau]]+(c5 eEM^5 \[Pi]^2)/45 ;

If[flagQED=="FULL",
(* This is for the e^2 terms that depend upon electron momentum *)
Asp[\[Tau]_,\[Omega]1_,\[Omega]2_]:=1/((Exp[Sqrt[\[Omega]1^2+\[Tau]^2]]+1)(Exp[Sqrt[\[Omega]2^2+\[Tau]^2]]+1)Sqrt[\[Omega]1^2+\[Tau]^2] Sqrt[\[Omega]2^2+\[Tau]^2]);
Bsp[\[Tau]_,\[Omega]1_,\[Omega]2_]:=Exp[Sqrt[\[Omega]2^2+\[Tau]^2]]/((Exp[Sqrt[\[Omega]1^2+\[Tau]^2]]+1)(Exp[Sqrt[\[Omega]2^2+\[Tau]^2]]+1)^2 Sqrt[\[Omega]1^2+\[Tau]^2]);
Csp[\[Tau]_,\[Omega]1_,\[Omega]2_]:=Exp[Sqrt[\[Omega]2^2+\[Tau]^2]]/((Exp[Sqrt[\[Omega]1^2+\[Tau]^2]]+1)(Exp[Sqrt[\[Omega]2^2+\[Tau]^2]]+1)^2) (Exp[Sqrt[\[Omega]1^2+\[Tau]^2]]/(Exp[Sqrt[\[Omega]1^2+\[Tau]^2]]+1)+Sqrt[\[Omega]2^2+\[Tau]^2]/Sqrt[\[Omega]1^2+\[Tau]^2] (Exp[Sqrt[\[Omega]2^2+\[Tau]^2]]-1)/(Exp[Sqrt[\[Omega]2^2+\[Tau]^2]]+1));

Ptil2log[\[Tau]_]:=(eEM^2 \[Tau]^2)/(4\[Pi]^4) NIntegrate[\[Omega]1 \[Omega]2 Log[Abs[(\[Omega]1+\[Omega]2)/(\[Omega]1-\[Omega]2)]]*(Asp[\[Tau],\[Omega]1,\[Omega]2]+Asp[\[Tau],\[Omega]2,\[Omega]1]),{\[Omega]1,0,Infinity},{\[Omega]2,0,\[Omega]1}];

G12log[\[Tau]_]:=(eEM^2 \[Tau])/(4\[Pi]^4) NIntegrate[\[Omega]1 \[Omega]2 Log[Abs[(\[Omega]1+\[Omega]2)/(\[Omega]1-\[Omega]2)]]*(Csp[\[Tau],\[Omega]1,\[Omega]2]-5Bsp[\[Tau],\[Omega]1,\[Omega]2]+Csp[\[Tau],\[Omega]2,\[Omega]1]-5Bsp[\[Tau],\[Omega]2,\[Omega]1]),{\[Omega]1,0,Infinity},{\[Omega]2,0,\[Omega]1}];
G22log[\[Tau]_]:=(eEM^2 \[Tau]^2)/(4\[Pi]^4) NIntegrate[\[Omega]1 \[Omega]2 Log[Abs[(\[Omega]1+\[Omega]2)/(\[Omega]1-\[Omega]2)]]*(Csp[\[Tau],\[Omega]1,\[Omega]2]-2Bsp[\[Tau],\[Omega]1,\[Omega]2]+Csp[\[Tau],\[Omega]2,\[Omega]1]-2Bsp[\[Tau],\[Omega]2,\[Omega]1]),{\[Omega]1,0,Infinity},{\[Omega]2,0,\[Omega]1}];
,Ptil2log[\[Tau]_]:=0;G12log[\[Tau]_]:=0;G22log[\[Tau]_]:=0;];


If[orderQED==2,
Pint[T\[Gamma]_]:=T\[Gamma]^4 ( Ptil2[me/T\[Gamma]]);
dPintdT[T\[Gamma]_]:=2/3 T\[Gamma]^3 ( G22[me/T\[Gamma]]-me/T\[Gamma] G12[me/T\[Gamma]]);
d2PintdT2[T\[Gamma]_]:=2T\[Gamma]^2 ( G22[me/T\[Gamma]]);
];
If[orderQED==3,
Pint[T\[Gamma]_]:=T\[Gamma]^4 ( Ptil2[me/T\[Gamma]]+Ptil3[me/T\[Gamma]]);
dPintdT[T\[Gamma]_]:=2/3 T\[Gamma]^3 ( G22[me/T\[Gamma]]-me/T\[Gamma] G12[me/T\[Gamma]]+G23[me/T\[Gamma]]-me/T\[Gamma] G13[me/T\[Gamma]]);
d2PintdT2[T\[Gamma]_]:=2T\[Gamma]^2 ( G22[me/T\[Gamma]]+G23[me/T\[Gamma]]);
];

If[orderQED==4,
Pint[T\[Gamma]_]:=T\[Gamma]^4 ( Ptil2[me/T\[Gamma]]+Ptil3[me/T\[Gamma]]+Ptil4[me/T\[Gamma]]);
dPintdT[T\[Gamma]_]:=2/3 T\[Gamma]^3 ( G22[me/T\[Gamma]]-me/T\[Gamma] G12[me/T\[Gamma]]+G23[me/T\[Gamma]]-me/T\[Gamma] G13[me/T\[Gamma]]+G24[me/T\[Gamma]]-me/T\[Gamma] G14[me/T\[Gamma]]);
d2PintdT2[T\[Gamma]_]:=2T\[Gamma]^2 ( G22[me/T\[Gamma]]+G23[me/T\[Gamma]]+G24[me/T\[Gamma]]);
];

If[orderQED==5,
Pint[T\[Gamma]_]:=T\[Gamma]^4 ( Ptil2[me/T\[Gamma]]+Ptil3[me/T\[Gamma]]+Ptil4[me/T\[Gamma]]+Ptil5[me/T\[Gamma]]);
dPintdT[T\[Gamma]_]:=2/3 T\[Gamma]^3 ( G22[me/T\[Gamma]]-me/T\[Gamma] G12[me/T\[Gamma]]+G23[me/T\[Gamma]]-me/T\[Gamma] G13[me/T\[Gamma]]+G24[me/T\[Gamma]]-me/T\[Gamma] G14[me/T\[Gamma]]+G25[me/T\[Gamma]]-me/T\[Gamma] G15[me/T\[Gamma]]);
d2PintdT2[T\[Gamma]_]:=2T\[Gamma]^2 ( G22[me/T\[Gamma]]+G23[me/T\[Gamma]]+G24[me/T\[Gamma]]+G25[me/T\[Gamma]]);
];

If[orderQED==6,
Pint[T\[Gamma]_]:=T\[Gamma]^4 ( Ptil2[me/T\[Gamma]]+Ptil3[me/T\[Gamma]]+Ptil4[me/T\[Gamma]]+Ptil5[me/T\[Gamma]]+Ptil2log[me/T\[Gamma]]);
dPintdT[T\[Gamma]_]:=2/3 T\[Gamma]^3 ( G22[me/T\[Gamma]]-me/T\[Gamma] G12[me/T\[Gamma]]+G23[me/T\[Gamma]]-me/T\[Gamma] G13[me/T\[Gamma]]+G24[me/T\[Gamma]]-me/T\[Gamma] G14[me/T\[Gamma]]+G25[me/T\[Gamma]]-me/T\[Gamma] G15[me/T\[Gamma]]+G22log[me/T\[Gamma]]-me/T\[Gamma] G12log[me/T\[Gamma]]);
d2PintdT2[T\[Gamma]_]:=2T\[Gamma]^2 ( G22[me/T\[Gamma]]+G23[me/T\[Gamma]]+G24[me/T\[Gamma]]+G25[me/T\[Gamma]]+G22log[me/T\[Gamma]]);
];

];


(* ::Input::Initialization:: *)
ClearAll[dataRates];
SetDirectory[NotebookDirectory[]];

If[FileExistsQ[dataFile["rate_coefficients_neutrinos.dat"]]==True,
dataRates=Import[dataFile["rate_coefficients_neutrinos.dat"],"Table",HeaderLines->3];
interpolOrder=1;
ClearAll[fa1func,fa2func,fa3func,fa4func,fs1func,fs2func,fs3func,fs4func,fn1func,fn2func,fn3func,fn4func];
fa1func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,2]]}],InterpolationOrder->interpolOrder];
fa2func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,3]]}],InterpolationOrder->interpolOrder];
fa3func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,4]]}],InterpolationOrder->interpolOrder];
fa4func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,5]]}],InterpolationOrder->interpolOrder];

fs1func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,6]]}],InterpolationOrder->interpolOrder];
fs2func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,7]]}],InterpolationOrder->interpolOrder];
fs3func[x_]=0;
fs4func[x_]=0;

fn1func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,10]]}],InterpolationOrder->interpolOrder];
fn2func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,11]]}],InterpolationOrder->interpolOrder];
fn3func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,12]]}],InterpolationOrder->interpolOrder];
fn4func=Interpolation[Thread[{dataRates[[All,1]],dataRates[[All,13]]}],InterpolationOrder->interpolOrder];

ClearAll[\[CapitalDelta]\[Rho]SM\[Nu]e,\[CapitalDelta]\[Rho]SM\[Nu]\[Mu],\[CapitalDelta]\[Rho]SM\[Nu],\[CapitalDelta]nSM\[Nu]e,\[CapitalDelta]nSM\[Nu]\[Mu],\[CapitalDelta]nSM\[Nu]];

Func[T1_,T2_,\[Mu]1_,\[Mu]2_]:=32 *fa1func[0]*(Exp[2 \[Mu]1/T1]T1^9-Exp[2 \[Mu]2/T2]T2^9)+32*fa3func[0](T1 T2)^4.5 *(Exp[2 \[Mu]2/T2]-Exp[2 \[Mu]1/T1])+56*fs1func[0]*T1^4 T2^4 Exp[\[Mu]1/T1]Exp[\[Mu]2/T2]*(T1-T2);

\[CapitalDelta]\[Rho]SM\[Nu]e[T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_,\[Mu]\[Nu]e_,\[Mu]\[Nu]\[Mu]_]:=FacMeVtos1   (GF^2)/\[Pi]^5 (  4*32((T\[Gamma]^9-Exp[2 \[Mu]\[Nu]e/T\[Nu]e]T\[Nu]e^9)((gL^2+gR^2)fa1func[me/T\[Gamma]]+gL gR fa2func[me/T\[Gamma]] )+(T\[Gamma] T\[Nu]e)^4.5 (Exp[2 \[Mu]\[Nu]e/T\[Nu]e]-1)((gL^2+gR^2)fa3func[me/T\[Gamma]]+gL gR fa4func[me/T\[Gamma]] ))+ 4*56* T\[Gamma]^4 *T\[Nu]e^4*Exp[\[Mu]\[Nu]e/T\[Nu]e]*(T\[Gamma]-T\[Nu]e)((gL^2+gR^2)fs1func[me/T\[Gamma]]+gL gR fs2func[me/T\[Gamma]] )+  2Func[T\[Nu]\[Mu],T\[Nu]e,\[Mu]\[Nu]\[Mu],\[Mu]\[Nu]e])/.{gL->geL,gR->geR};

\[CapitalDelta]\[Rho]SM\[Nu]\[Mu][T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_,\[Mu]\[Nu]e_,\[Mu]\[Nu]\[Mu]_]:=FacMeVtos1   (GF^2)/\[Pi]^5 (4*32((T\[Gamma]^9-Exp[2 \[Mu]\[Nu]\[Mu]/T\[Nu]\[Mu]]T\[Nu]\[Mu]^9)((gL^2+gR^2)fa1func[me/T\[Gamma]]+gL gR fa2func[me/T\[Gamma]] )+(T\[Gamma] T\[Nu]\[Mu])^4.5 (Exp[2 \[Mu]\[Nu]\[Mu]/T\[Nu]\[Mu]]-1)((gL^2+gR^2)fa3func[me/T\[Gamma]]+gL gR fa4func[me/T\[Gamma]] ))+4*56* T\[Gamma]^4 *T\[Nu]\[Mu]^4*Exp[\[Mu]\[Nu]\[Mu]/T\[Nu]\[Mu]]*(T\[Gamma]-T\[Nu]\[Mu])((gL^2+gR^2)fs1func[me/T\[Gamma]]+gL gR fs2func[me/T\[Gamma]] )-Func[T\[Nu]\[Mu],T\[Nu]e,\[Mu]\[Nu]\[Mu],\[Mu]\[Nu]e])/.{gL->gmuL,gR->gmuR};

\[CapitalDelta]\[Rho]SM\[Nu][T\[Gamma]_,T\[Nu]_,\[Mu]\[Nu]_]:=1/3 (\[CapitalDelta]\[Rho]SM\[Nu]e[T\[Gamma],T\[Nu],T\[Nu],\[Mu]\[Nu],\[Mu]\[Nu]]+2\[CapitalDelta]\[Rho]SM\[Nu]\[Mu][T\[Gamma],T\[Nu],T\[Nu],\[Mu]\[Nu],\[Mu]\[Nu]]);

(* Number Density Transfer Rates: \[Delta]n/\[Delta]t *)
\[CapitalDelta]nSM\[Nu]e[T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_,\[Mu]\[Nu]e_,\[Mu]\[Nu]\[Mu]_]:=FacMeVtos1*8 * (GF^2)/\[Pi]^5 ( 4 ((gL^2+gR^2)fn1func[me/T\[Gamma]]+gL gR fn2func[me/T\[Gamma]])(T\[Gamma]^8-Exp[2 \[Mu]\[Nu]e/T\[Nu]e]T\[Nu]e^8)+  4 ((gL^2+gR^2)fn3func[me/T\[Gamma]]+gL gR fn4func[me/T\[Gamma]])T\[Gamma]^4 T\[Nu]e^4 (Exp[2 \[Mu]\[Nu]e/T\[Nu]e]-1)+ 2 fn1func[0](T\[Nu]\[Mu]^8 Exp[2 \[Mu]\[Nu]\[Mu]/T\[Nu]\[Mu]]-T\[Nu]e^8 Exp[2 \[Mu]\[Nu]e/T\[Nu]e]) + 2 fn3func[0]T\[Nu]\[Mu]^4 T\[Nu]e^4 (Exp[2 \[Mu]\[Nu]e/T\[Nu]e]-Exp[2 \[Mu]\[Nu]\[Mu]/T\[Nu]\[Mu]]) )/.{gL->geL,gR->geR};


\[CapitalDelta]nSM\[Nu]\[Mu][T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_,\[Mu]\[Nu]e_,\[Mu]\[Nu]\[Mu]_]:=FacMeVtos1*8 * (GF^2)/\[Pi]^5 (4 ((gL^2+gR^2)fn1func[me/T\[Gamma]]+gL gR fn2func[me/T\[Gamma]])(T\[Gamma]^8-Exp[2 \[Mu]\[Nu]\[Mu]/T\[Nu]\[Mu]]T\[Nu]\[Mu]^8)+4 ((gL^2+gR^2)fn3func[me/T\[Gamma]]+gL gR fn4func[me/T\[Gamma]])T\[Gamma]^4 T\[Nu]\[Mu]^4 (Exp[2 \[Mu]\[Nu]\[Mu]/T\[Nu]\[Mu]]-1)- (fn1func[0](T\[Nu]\[Mu]^8 Exp[2 \[Mu]\[Nu]\[Mu]/T\[Nu]\[Mu]]-T\[Nu]e^8 Exp[2 \[Mu]\[Nu]e/T\[Nu]e]) +  fn3func[0]T\[Nu]\[Mu]^4 T\[Nu]e^4 (Exp[2 \[Mu]\[Nu]e/T\[Nu]e]-Exp[2 \[Mu]\[Nu]\[Mu]/T\[Nu]\[Mu]]) ) )/.{gL->gmuL,gR->gmuR};

\[CapitalDelta]nSM\[Nu][T\[Gamma]_,T\[Nu]_,\[Mu]\[Nu]_]:=1/3 (\[CapitalDelta]nSM\[Nu]e[T\[Gamma],T\[Nu],T\[Nu],\[Mu]\[Nu],\[Mu]\[Nu]]+2\[CapitalDelta]nSM\[Nu]\[Mu][T\[Gamma],T\[Nu],T\[Nu],\[Mu]\[Nu],\[Mu]\[Nu]]);
,Print["\[Nu]\[Nu] interactions are not loaded as the file is missing"]];


(* ::Input::Initialization:: *)
(* Massless Species : n, \[Rho], p  *)

ClearAll[nBE,nFD,\[Rho]BE,\[Rho]FD,pBE,pFD,dnBEdT,dnBEd\[Mu],d\[Rho]BEdT,d\[Rho]BEd\[Mu],dnFDdT,dnFDd\[Mu],d\[Rho]FDdT,d\[Rho]FDd\[Mu]];
nBE[T_,\[Mu]_]:=(T^3 PolyLog[3,E^(\[Mu]/T)])/\[Pi]^2;
nFD[T_,\[Mu]_]:=-((T^3 PolyLog[3,-E^((\[Mu]/T))])/\[Pi]^2);
\[Rho]BE[T_,\[Mu]_]:=(3 T^4 PolyLog[4,E^(\[Mu]/T)])/\[Pi]^2;
\[Rho]FD[T_,\[Mu]_]:=-((3 T^4 PolyLog[4,-E^((\[Mu]/T))])/\[Pi]^2);
pBE[T_,\[Mu]_]:=1/3 \[Rho]BE[T,\[Mu]];
pFD[T_,\[Mu]_]:=1/3 \[Rho]FD[T,\[Mu]];

(* Massless Species : \!\(
\*SubscriptBox[\(\[PartialD]\), \(T\)]\ \ 
\*SubscriptBox[\(\[PartialD]\), \(\[Mu]\)]\)  *)
dnBEdT[T_,\[Mu]_]:=(T (-\[Mu] PolyLog[2,E^(\[Mu]/T)]+3 T PolyLog[3,E^(\[Mu]/T)]))/\[Pi]^2;
dnBEd\[Mu][T_,\[Mu]_]:=(T^2 PolyLog[2,E^(\[Mu]/T)])/\[Pi]^2;
d\[Rho]BEdT[T_,\[Mu]_]:=(3 T^2 (-\[Mu] PolyLog[3,E^(\[Mu]/T)]+4 T PolyLog[4,E^(\[Mu]/T)]))/\[Pi]^2;
d\[Rho]BEd\[Mu][T_,\[Mu]_]:=(3 T^3 PolyLog[3,E^(\[Mu]/T)])/\[Pi]^2;

dnFDdT[T_,\[Mu]_]:=(T (\[Mu] PolyLog[2,-E^((\[Mu]/T))]-3 T PolyLog[3,-E^((\[Mu]/T))]))/\[Pi]^2;
dnFDd\[Mu][T_,\[Mu]_]:=-((T^2 PolyLog[2,-E^((\[Mu]/T))])/\[Pi]^2);
d\[Rho]FDdT[T_,\[Mu]_]:=(3 T^2 (\[Mu] PolyLog[3,-E^((\[Mu]/T))]-4 T PolyLog[4,-E^((\[Mu]/T))]))/\[Pi]^2;
d\[Rho]FDd\[Mu][T_,\[Mu]_]:=-((3 T^3 PolyLog[3,-E^((\[Mu]/T))])/\[Pi]^2);

(* Massive Species : n, \[Rho], p  *)

ClearAll[nBEM,nFDM,nMBM,\[Rho]BEM,\[Rho]FDM,pBEM,pFDM,dndTBEM,dnd\[Mu]BEM,d\[Rho]dTBEM,d\[Rho]d\[Mu]BEM,dndTFDM,d\[Rho]dTFDM,dnd\[Mu]FDM,d\[Rho]d\[Mu]FDM];
nBEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[(Exp[\[Mu]/T (n+1)] 1^n m^2 T BesselK[2,(m (1+n))/T])/(1+n),{n,0,nBesselmaxBSM}]);
nFDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[(Exp[\[Mu]/T (n+1)] (-1)^n m^2 T BesselK[2,(m (1+n))/T])/(1+n),{n,0,nBesselmaxBSM}]);
nMBM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (E^(\[Mu]/T) m^2 T BesselK[2,m/T]);
\[Rho]BEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[(Exp[\[Mu]/T (n+1)] 1^n m^2 T (m (1+n) BesselK[1,(m (1+n))/T]+3 T BesselK[2,(m (1+n))/T]))/(1+n)^2,{n,0,nBesselmaxBSM}]);
\[Rho]FDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[(Exp[\[Mu]/T (n+1)] (-1)^n m^2 T (m (1+n) BesselK[1,(m (1+n))/T]+3 T BesselK[2,(m (1+n))/T]))/(1+n)^2,{n,0,nBesselmaxBSM}]);
pBEM[T_,\[Mu]_,m_]:=1/(6 \[Pi]^2) (Sum[(3 Exp[\[Mu]/T (n+1)] 1^n m^2 T^2 BesselK[2,(m (1+n))/T])/(1+n)^2,{n,0,nBesselmaxBSM}]);
pFDM[T_,\[Mu]_,m_]:=1/(6 \[Pi]^2) (Sum[(3 Exp[\[Mu]/T (n+1)] (-1)^n m^2 T^2 BesselK[2,(m (1+n))/T])/(1+n)^2,{n,0,nBesselmaxBSM}]);

(* Massive Species : \!\(
\*SubscriptBox[\(\[PartialD]\), \(T\)]\ \ 
\*SubscriptBox[\(\[PartialD]\), \(\[Mu]\)]\)  *)

dndTBEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[(E^(((1+n) \[Mu])/T) 1^n m^2 (m BesselK[1,(m (1+n))/T]-((-3 T+\[Mu]+n \[Mu]) BesselK[2,(m (1+n))/T])/(1+n)))/T,{n,0,nBesselmaxBSM}]);
dnd\[Mu]BEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[E^(((1+n) \[Mu])/T) 1^n m^2 BesselK[2,(m (1+n))/T],{n,0,nBesselmaxBSM}]);
d\[Rho]dTBEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[1/((1+n)^2 T) E^(((1+n) \[Mu])/T) 1^n m (m (m^2 (1+n)^2-3 T (-4 T+\[Mu]+n \[Mu])) BesselK[0,(m (1+n))/T]-((m^2 (1+n)^2 (-5 T+\[Mu]+n \[Mu])+6 T^2 (-4 T+\[Mu]+n \[Mu])) BesselK[1,(m (1+n))/T])/(1+n)),{n,0,nBesselmaxBSM}]);
d\[Rho]d\[Mu]BEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[(E^(((1+n) \[Mu])/T) 1^n m^2 (m (1+n) BesselK[1,(m (1+n))/T]+3 T BesselK[2,(m (1+n))/T]))/(1+n),{n,0,nBesselmaxBSM}]);

dndTFDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[(E^(((1+n) \[Mu])/T) (-1)^n m^2 (m BesselK[1,(m (1+n))/T]-((-3 T+\[Mu]+n \[Mu]) BesselK[2,(m (1+n))/T])/(1+n)))/T,{n,0,nBesselmaxBSM}]);

d\[Rho]dTFDM[T_,\[Mu]_,m_]:=
1/(2 \[Pi]^2) (Sum[1/((1+n)^2 T) E^(((1+n) \[Mu])/T) (-1)^n m (m (m^2 (1+n)^2-3 T (-4 T+\[Mu]+n \[Mu])) BesselK[0,(m (1+n))/T]-((m^2 (1+n)^2 (-5 T+\[Mu]+n \[Mu])+6 T^2 (-4 T+\[Mu]+n \[Mu])) BesselK[1,(m (1+n))/T])/(1+n)),{n,0,nBesselmaxBSM}]);
dnd\[Mu]FDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[E^(((1+n) \[Mu])/T) (-1)^n m^2 BesselK[2,(m (1+n))/T],{n,0,nBesselmaxBSM}]);
d\[Rho]d\[Mu]FDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) (Sum[(E^(((1+n) \[Mu])/T) (-1)^n m^2 (m (1+n) BesselK[1,(m (1+n))/T]+3 T BesselK[2,(m (1+n))/T]))/(1+n),{n,0,nBesselmaxBSM}]);

(* Case where one choses to write the thermodynamic functions exactly *)
If[flagthermo=="FULL", 
ClearAll[nBEM,nFDM,nMBM,\[Rho]BEM,\[Rho]FDM,pBEM,pFDM,dndTBEM,dnd\[Mu]BEM,d\[Rho]dTBEM,d\[Rho]d\[Mu]BEM,dndTFDM,d\[Rho]dTFDM,dnd\[Mu]FDM,d\[Rho]d\[Mu]FDM];
nBEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] 1/(Exp[Enred-\[Mu]/T]-1),{Enred,m/T,\[Infinity]}];
nFDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] 1/(Exp[Enred-\[Mu]/T]+1),{Enred,m/T,\[Infinity]}];
nMBM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] 1/Exp[Enred-\[Mu]/T],{Enred,m/T,\[Infinity]}];
\[Rho]BEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^4 NIntegrate[Enred^2 Sqrt[Enred^2-m^2/T^2] 1/(Exp[Enred-\[Mu]/T]-1),{Enred,m/T,\[Infinity]}];
\[Rho]FDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^4 NIntegrate[Enred^2 Sqrt[Enred^2-m^2/T^2] 1/(Exp[Enred-\[Mu]/T]+1),{Enred,m/T,\[Infinity]}];
pBEM[T_,\[Mu]_,m_]:=1/(6 \[Pi]^2) T^4 NIntegrate[(Enred^2-m^2/T^2)^(3/2) 1/(Exp[Enred-\[Mu]/T]-1),{Enred,m/T,\[Infinity]}];
pFDM[T_,\[Mu]_,m_]:=1/(6 \[Pi]^2) T^4 NIntegrate[(Enred^2-m^2/T^2)^(3/2) 1/(Exp[Enred-\[Mu]/T]+1),{Enred,m/T,\[Infinity]}];

(* Massive Species : \!\(
\*SubscriptBox[\(\[PartialD]\), \(T\)]\ \ 
\*SubscriptBox[\(\[PartialD]\), \(\[Mu]\)]\)  *)

dndTBEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] ((Enred T-\[Mu]) Csch[1/2 (Enred-\[Mu]/T)]^2)/(4 T^2),{Enred,m/T,\[Infinity]}];
dnd\[Mu]BEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] Csch[1/2 (Enred-\[Mu]/T)]^2/(4 T),{Enred,m/T,\[Infinity]}];
d\[Rho]dTBEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^4 NIntegrate[Enred^2 Sqrt[Enred^2-m^2/T^2] ((Enred T-\[Mu]) Csch[1/2 (Enred-\[Mu]/T)]^2)/(4 T^2),{Enred,m/T,\[Infinity]}];
d\[Rho]d\[Mu]BEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^4 NIntegrate[Enred^2 Sqrt[Enred^2-m^2/T^2] Csch[1/2 (Enred-\[Mu]/T)]^2/(4 T),{Enred,m/T,\[Infinity]}];

dndTFDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^2 Quiet[NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] ((Enred -\[Mu]/T) Sech[(Enred -\[Mu]/T)/2]^2)/4,{Enred,m/T,\[Infinity]}]];

d\[Rho]dTFDM[T_,\[Mu]_,m_]:=
1/(2 \[Pi]^2) T^3 Quiet[NIntegrate[Enred^2 Sqrt[Enred^2-m^2/T^2] ((Enred -\[Mu]/T) Sech[(Enred -\[Mu]/T)/2]^2)/4,{Enred,m/T,\[Infinity]}]];

dnd\[Mu]FDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^2 Quiet[NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] 1/(2(Cosh[Enred -\[Mu]/T]+1)),{Enred,m/T,\[Infinity]}]];
d\[Rho]d\[Mu]FDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 Quiet[NIntegrate[Enred^2 Sqrt[Enred^2-m^2/T^2] 1/(2(Cosh[Enred -\[Mu]/T]+1)),{Enred,m/T,\[Infinity]}]];
];


(* Entropy Densities *)
ClearAll[sFD,sFDM,sBE,sBEM];

sFD[T_,\[Mu]_]:= (\[Rho]FD[T,\[Mu]]+ pFD[T,\[Mu]]-\[Mu] nFD[T,\[Mu]])/T;
sFDM[T_,\[Mu]_,m_]:= (\[Rho]FDM[T,\[Mu],m]+ pFDM[T,\[Mu],m]-\[Mu] nFDM[T,\[Mu],m])/T;
sBE[T_,\[Mu]_]:= (\[Rho]BE[T,\[Mu]]+ pBE[T,\[Mu]]-\[Mu] nBE[T,\[Mu]])/T;
sBEM[T_,\[Mu]_,m_]:= (\[Rho]BEM[T,\[Mu],m]+ pBEM[T,\[Mu],m]-\[Mu] nBEM[T,\[Mu],m])/T;

